"""add papaz_kacti

Revision ID: 421671bf850b
Revises: 20260730_0010
Create Date: 2026-08-02 01:29:59.412700
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '421671bf850b'
down_revision: str | None = '20260730_0010'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papaz_kacti_games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('player_one_user_id', sa.UUID(), nullable=False),
    sa.Column('player_two_user_id', sa.UUID(), nullable=True),
    sa.Column('player_three_user_id', sa.UUID(), nullable=True),
    sa.Column('player_four_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('loser_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loser_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_four_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_one_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_three_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_two_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papaz_kacti_games_room_id'), 'papaz_kacti_games', ['room_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_papaz_kacti_games_room_id'), table_name='papaz_kacti_games')
    op.drop_table('papaz_kacti_games')
    # ### end Alembic commands ###
